backend:
  name: github
  repo: z-bluue/my-blog
  branch: main
  base_url: https://wjh.wang
  auth_endpoint: /api/auth
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: 'blog'
    label: '博客'
    folder: 'content/posts/Mylog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '正文', name: 'body', widget: 'markdown' }